INSERT INTO TB_USERS(name, password, username) VALUES ('admin','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','admin@master');
INSERT INTO TB_USERS(name, password, username) VALUES ('maria','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','maria@maria');
INSERT INTO TB_USERS(name, password, username) VALUES ('joao','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','joao@joao');
INSERT INTO TB_USERS(name, password, username) VALUES ('marcos','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','marcos@marcos');
INSERT INTO TB_USERS(name, password, username) VALUES ('ana','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','ana@ana');
INSERT INTO TB_USERS(name, password, username) VALUES ('pedro','$2a$12$CtVEGjY3UJUJB91S5OrJjOxFIOQ9h1TGxrMAMWkBJOVMDQ11fq6RK','pedro@pedro');

INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_OWNER',1);
INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_OWNER',2);
INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_OWNER',3);
INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_USER',4);
INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_USER',5);
INSERT INTO TB_AUTHORITIES(authority, user_id) VALUES('ROLE_USER',6);

INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Facebook',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Tinder',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('WhatsApp',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Linkedin',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Instagram',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Youtube',1,1);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Gmail',1,2);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Gympass',1,2);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Github',1,2);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Uber',0,2);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Tik-Tok',0,3);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Telegram',0,3);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Spotfy',0,3);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Snapchat',0,3);
INSERT INTO TB_PRODUCTS (name, published, user_id) VALUES ('Messenger',0,3);

INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir que o usuário saiba quem visitou seu perfil.','Pending review','Visitantes',1,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Aumentar numero de likes para não assinantes.','Pending review','Likes ',2,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Saber quem visitou seu perfil.','Pending review','Perfil',2,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir que o usuário ocultar se esta online.','Pending review','Usuario online',3,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir aos usuários enviar gifs animados nas mensagens.','Pending review','Gifs animados',3,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir que o usuário envie qualquer tipo de arquivo para outros usuários.','Pending review','Envio de documentos',3,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Recomendar melhores vagas de empregos ao usuário.','Pending review','Vagas de emprego',4,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Área de inclusão certificados para o perfil.','Pending review','Certificados',4,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Usuários conta premium poderá anunciar vagas de emprego.','Pending review','Anuncios',4,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Habilitar filtros nas postagens de fotos.','Pending review','Filtros',5,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Habilitar ícone de dislike em postagens.','Pending review','Dislike',5,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Mostrar a contagem de dislikes para postagens.','Pending review','Visualizar dislike',6,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Usuários de conta premium podem baixar os vídeos da plataforma.','Pending review','Baixar videos',6,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Habilitar botão para usuário visualizar o vídeo em horário definido.','Pending review','Visualizar mais tarde',6,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Usuários poderão anunciar seus produtos na plataforma.','Pending review','Anuncios',1,1);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Backup automático das mensagens mais antigas.','Pending review','Backup',7,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Arquivos em anexo poderão ter ate 250mb.','Pending review','Anexos de arquivos',7,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('E-mails suspeitos cairão diretamente na caixa de spam.','Pending review','Emails suspeitos',7,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Exibição de anúncios de lojas ao redor do local de check-in.','Pending review','Anuncios',8,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Check-in poderá ser realizado em até 40 min.','Pending review','Tempo de check-in',8,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Integrar com API do aplicativo Strava.','Pending review','Integração com strava',8,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Disponibilização de API para programadores.','Pending review','API',9,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Integração com Linkedin para facilitar recrutamento e seleção.','Pending review','Integração com Linkedin',9,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Mostrar as avaliações dos motoristas da plataforma.','Pending review','Reputação de motoristas',10,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Motorista poderá escolher homem,mulher ou ambos para as corridas.','Pending review','Seleção de passageiros',10,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Passageiros poderão avaliar o motorista no critério de até 5 estrelas.','Pending review','Avaliações',10,2);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Limitar o numero de postagens de mulheres que rebolam demais.','Pending review','Limitação em postagens',11,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Habilitar contagem de dislikes para postagens.','Pending review','Dislike',11,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir aos usuários excluir comentários maldosos de suas postagens.','Pending review','Excluir comentários maldosos',11,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir usuários denunciar perfis fake e hostis na plataforma.','Pending review','Denunciar perfil',11,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Habilitar envio de qualquer tipo de arquivo.','Pending review','Envio de arquivos',12,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permitir ao usuário desativar confirmação de leitura de mensagem.','Pending review','Desativar visualização',12,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Permite recomendar musicas para os amigos.','Pending review','Recomendar musicas ',13,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Sem exibição de propagandas para usuários premium.','Pending review','Usuários premium',13,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Limitar tempo das postagens para 10 minutos, no minimo.','Pending review','Limitar tempo',14,3);
INSERT INTO TB_FEATURES (description, status, title, product_id, user_id) VALUES ('Aplicar filtro para mensagens com conteúdo improprio.','Pending review','Filtros para mensagens',15,3);
